[tasks.build-frontend]
description = "build yew frontend for release"
install_crate = "trunk"
command = "trunk"
args = ["build", "--release", "--dist", "../static"]

[tasks.default]
dependencies = ["build-frontend"]