//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

pub mod prelude;

pub mod city;
pub mod company;
pub mod contact;
pub mod country;
pub mod department;
pub mod job_title;
pub mod postal_code;
pub mod state;
pub mod street_address;
