//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

pub use super::city::Entity as City;
pub use super::company::Entity as Company;
pub use super::contact::Entity as Contact;
pub use super::country::Entity as Country;
pub use super::department::Entity as Department;
pub use super::job_title::Entity as JobTitle;
pub use super::postal_code::Entity as PostalCode;
pub use super::state::Entity as State;
pub use super::street_address::Entity as StreetAddress;
